version: '3'
services:
  web:
    build: .
    ports:
      - "5151:5000"
  
  mongodb:
    container_name: mongodb
    image: mongo
    ports:
      - "27018:27017"
    restart: always
    #volumes:
    #  - mongo_data:/data/db

#volumes:
  #mongo_data: